version: 2.1

orbs:
  codecov: codecov/codecov@1.0.5

jobs:
  build-and-test:
    docker:
      - image: circleci/python:3.8.3
      
    working_directory: ~/cazy_webscraper

    steps:
      - checkout

      - restore_cache:
          keys:
            - cazy_wbscrpr-{{ .Branch }}-{{ checksum "requirements.txt" }}-{{ checksum "requirements-dev.txt" }}-{{ checksum "requirements-pip.txt" }}
            - cazy_wbscrpr-

      - run:
          name: install dependencies
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install -r requirements.txt
            pip install -r requirements-dev.txt
            pip install -r requirements-pip.txt

      - save_cache:
          paths:
            - ./venv
          key: cazy_wbscrpr-{{ .Branch }}-{{ checksum "requirements.txt" }}-{{ checksum "requirements-dev.txt" }}-{{ checksum "requirements-pip.txt" }}

      - run:
          name: install package
          command: |
            . venv/bin/activate
            pip install -e .

      - run:
          name: run tests
          command: |
            . venv/bin/activate
            pytest -v --cov=scraper --cov-report xml:.coverage.xml

      - store_artifacts:
          path: tests/test_output
          destination: tests/test_output
      - store_artifacts:
          path: .coverage.xml
          destination: .coverage.xml

      - codecov/upload:
          file: .coverage.xml

workflows:
  main:
    jobs:
      - build-and-test
